server:
  port: ${PORT}

grpc:
  client:
    booking-service:
      address: 'discovery:///booking-service'
      negotiation-type: plaintext

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql

  flyway:
    validate-on-migrate: true
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KC_INTERNAL_BASE_URL}/realms/${KC_REALM}/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: ${KF_SERVER_URL}
    properties:
      schema.registry.url: ${SC_REGISTRY_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    consumer:
      group-id: ${KF_CONSUMER_GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
        specific.protobuf.value.type: ${KF_PROTOBUF_TYPE}

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default: # Define a base config to reuse for other services
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        event-consumer-buffer-size: 10
        record-exceptions:
          - io.grpc.StatusRuntimeException
          - java.util.concurrent.TimeoutException
    instances:
      booking-service:
        baseConfig: default
        # --- Analysis Window ---
        sliding-window-size: ${CB_WINDOW_SIZE:10}
        minimum-number-of-calls: ${CB_MINIMUM_CALLS:5}
        
        # --- Thresholds ---
        failure-rate-threshold: ${CB_FAILURE_THRESHOLD:50}
        
        # --- Recovery Logic ---
        wait-duration-in-open-state: ${CB_WAIT_DURATION:10s}
        permitted-number-of-calls-in-half-open-state: ${CB_HALF_OPEN_CALLS:3}
        record-failure-predicate: com.eventapp.paymentservice.config.GrpcFailurePredicate
        
  retry:
    retry-aspect-order: 2
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - io.grpc.StatusRuntimeException
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException
    instances:
      booking-service:
        base-config: default
        retry-exception-predicate: com.eventapp.paymentservice.config.GrpcFailurePredicate
          
app:
  schema-registry:
    url: ${SC_REGISTRY_URL}
  security:
    hmac-secret: ${HMAC_SECURITY}
